<?php
session_start();
require_once('../../tcpdf/tcpdf.php');
include '../../config.php';

$record_id = $_GET['id'] ?? null;

if (!$record_id) {
    die('Invalid record ID');
}

// ✅ Get clinic info using session clinic_id
$clinic_id = $_SESSION['clinic_id'] ?? null;
if (!$clinic_id) {
    die('No clinic session found.');
}

$clinic_id = $_SESSION['clinic_id'];

// ✅ Fetch the clinic info (name + logo)
$stmtClinic = $pdo->prepare("SELECT clinic_name, logo FROM clinics WHERE clinic_id = ?");
$stmtClinic->execute([$clinic_id]);
$clinic = $stmtClinic->fetch(PDO::FETCH_ASSOC);

$clinic_name = $clinic['clinic_name'] ?? 'VetCareSys Veterinary Clinic';
$clinic_logo = !empty($clinic['logo']) 
    ? "../../uploads/logos/" . htmlspecialchars($clinic['logo']) 
    : "../../assets/logo.png";

// ✅ Fetch pet record data
$stmt = $pdo->prepare("
    SELECT pr.*, p.pet_name, p.breed, p.birth_date, u.name AS owner_name, rt.template_name
    FROM pet_records pr
    JOIN pets p ON pr.pet_id = p.pet_id
    JOIN users u ON p.owner_id = u.user_id
    JOIN record_templates rt ON pr.template_id = rt.template_id
    WHERE pr.record_id = ?
");
$stmt->execute([$record_id]);
$record = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$record) {
    die('Record not found');
}

$data = json_decode($record['data'], true);

// ✅ Create PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetTitle('Pet Record - ' . $record['pet_name']);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 11);

// ✅ Clinic Header
$html = '
<div style="text-align:center;">
    <img src="' . $clinic_logo . '" width="80" height="80" style="object-fit:contain;"><br>
    <h2 style="color:#007bff;">' . htmlspecialchars($clinic_name) . '</h2>
    <p style="color:gray;">Official Pet Medical Record</p>
</div>
<hr>
<h4>Pet Information</h4>
<table border="1" cellpadding="6">
<tr><td><b>Pet Name:</b></td><td>' . htmlspecialchars($record['pet_name']) . '</td></tr>
<tr><td><b>Owner:</b></td><td>' . htmlspecialchars($record['owner_name']) . '</td></tr>
<tr><td><b>Breed:</b></td><td>' . htmlspecialchars($record['breed']) . '</td></tr>
<tr><td><b>Birthdate:</b></td><td>' . htmlspecialchars($record['birth_date']) . '</td></tr>
<tr><td><b>Record Type:</b></td><td>' . htmlspecialchars($record['template_name']) . '</td></tr>
<tr><td><b>Date Recorded:</b></td><td>' . date("M d, Y h:i A", strtotime($record['date_recorded'])) . '</td></tr>
</table>
<br><h4>Consultation / Medical Details</h4>
<table border="1" cellpadding="6">
';

if (!empty($data)) {
    foreach ($data as $label => $value) {
        $html .= '<tr><td><b>' . ucwords(str_replace('_', ' ', $label)) . ':</b></td><td>' . nl2br(htmlspecialchars($value)) . '</td></tr>';
    }
} else {
    $html .= '<tr><td colspan="2">No consultation data available.</td></tr>';
}

$html .= '
</table><br><br>
<p><b>Attending Veterinarian:</b> ____________________________</p>
<p><b>Date:</b> ____________________________</p>
<hr>
<p style="text-align:center;font-size:10px;color:gray;">Generated by VetCareSys © ' . date('Y') . ' | For Veterinary Use Only</p>
';

// ✅ Write HTML content to PDF
$pdf->writeHTML($html, true, false, true, false, '');

// ✅ Output PDF to browser
$pdf->Output('Pet_Record_' . preg_replace('/[^A-Za-z0-9_\-]/', '_', $record['pet_name']) . '.pdf', 'I');
?>
